/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BienEtreRouteImport } from './routes/bien-etre'
import { Route as ConceptRouteImport } from './routes/concept'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SoinsIndexRouteImport } from './routes/soins.index'
import { Route as SoinsSlugRouteImport } from './routes/soins.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BienEtreRoute = BienEtreRouteImport.update({
  id: '/bien-etre',
  path: '/bien-etre',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptRoute = ConceptRouteImport.update({
  id: '/concept',
  path: '/concept',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SoinsIndexRoute = SoinsIndexRouteImport.update({
  id: '/soins/',
  path: '/soins/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoinsSlugRoute = SoinsSlugRouteImport.update({
  id: '/soins/$slug',
  path: '/soins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bien-etre': typeof BienEtreRoute
  '/concept': typeof ConceptRoute
  '/contact': typeof ContactRoute
  '/soins/$slug': typeof SoinsSlugRoute
  '/soins/': typeof SoinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bien-etre': typeof BienEtreRoute
  '/concept': typeof ConceptRoute
  '/contact': typeof ContactRoute
  '/soins/$slug': typeof SoinsSlugRoute
  '/soins': typeof SoinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bien-etre': typeof BienEtreRoute
  '/concept': typeof ConceptRoute
  '/contact': typeof ContactRoute
  '/soins/$slug': typeof SoinsSlugRoute
  '/soins/': typeof SoinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/bien-etre' | '/concept' | '/contact' | '/soins/$slug' | '/soins/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bien-etre' | '/concept' | '/contact' | '/soins/$slug' | '/soins'
  id:
    | '__root__'
    | '/'
    | '/bien-etre'
    | '/concept'
    | '/contact'
    | '/soins/$slug'
    | '/soins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BienEtreRoute: typeof BienEtreRoute
  ConceptRoute: typeof ConceptRoute
  ContactRoute: typeof ContactRoute
  SoinsSlugRoute: typeof SoinsSlugRoute
  SoinsIndexRoute: typeof SoinsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bien-etre': {
      id: '/bien-etre'
      path: '/bien-etre'
      fullPath: '/bien-etre'
      preLoaderRoute: typeof BienEtreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept': {
      id: '/concept'
      path: '/concept'
      fullPath: '/concept'
      preLoaderRoute: typeof ConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soins/': {
      id: '/soins/'
      path: '/soins'
      fullPath: '/soins/'
      preLoaderRoute: typeof SoinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soins/$slug': {
      id: '/soins/$slug'
      path: '/soins/$slug'
      fullPath: '/soins/$slug'
      preLoaderRoute: typeof SoinsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BienEtreRoute: BienEtreRoute,
  ConceptRoute: ConceptRoute,
  ContactRoute: ContactRoute,
  SoinsSlugRoute: SoinsSlugRoute,
  SoinsIndexRoute: SoinsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
