/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BienEtreRouteImport } from './routes/bien-etre'
import { Route as ConceptRouteImport } from './routes/concept'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CryolipolyseDoleRouteImport } from './routes/cryolipolyse-dole'
import { Route as CryolipolyseVentreDoleRouteImport } from './routes/cryolipolyse-ventre-dole'
import { Route as EpilationLaserDoleRouteImport } from './routes/epilation-laser-dole'
import { Route as EpilationLaserJambesDoleRouteImport } from './routes/epilation-laser-jambes-dole'
import { Route as EpilationLaserMaillotDoleRouteImport } from './routes/epilation-laser-maillot-dole'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolutionMinceurDoleRouteImport } from './routes/solution-minceur-dole'
import { Route as YogaDoleRouteImport } from './routes/yoga-dole'
import { Route as AdminConfigDotymlRouteImport } from './routes/admin/config[.]yml'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as SoinsIndexRouteImport } from './routes/soins.index'
import { Route as SoinsSlugRouteImport } from './routes/soins.$slug'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BienEtreRoute = BienEtreRouteImport.update({
  id: '/bien-etre',
  path: '/bien-etre',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptRoute = ConceptRouteImport.update({
  id: '/concept',
  path: '/concept',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CryolipolyseDoleRoute = CryolipolyseDoleRouteImport.update({
  id: '/cryolipolyse-dole',
  path: '/cryolipolyse-dole',
  getParentRoute: () => rootRouteImport,
} as any)
const CryolipolyseVentreDoleRoute = CryolipolyseVentreDoleRouteImport.update({
  id: '/cryolipolyse-ventre-dole',
  path: '/cryolipolyse-ventre-dole',
  getParentRoute: () => rootRouteImport,
} as any)
const EpilationLaserDoleRoute = EpilationLaserDoleRouteImport.update({
  id: '/epilation-laser-dole',
  path: '/epilation-laser-dole',
  getParentRoute: () => rootRouteImport,
} as any)
const EpilationLaserJambesDoleRoute =
  EpilationLaserJambesDoleRouteImport.update({
    id: '/epilation-laser-jambes-dole',
    path: '/epilation-laser-jambes-dole',
    getParentRoute: () => rootRouteImport,
  } as any)
const EpilationLaserMaillotDoleRoute =
  EpilationLaserMaillotDoleRouteImport.update({
    id: '/epilation-laser-maillot-dole',
    path: '/epilation-laser-maillot-dole',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionMinceurDoleRoute = SolutionMinceurDoleRouteImport.update({
  id: '/solution-minceur-dole',
  path: '/solution-minceur-dole',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaDoleRoute = YogaDoleRouteImport.update({
  id: '/yoga-dole',
  path: '/yoga-dole',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigDotymlRoute = AdminConfigDotymlRouteImport.update({
  id: '/admin/config.yml',
  path: '/admin/config.yml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SoinsIndexRoute = SoinsIndexRouteImport.update({
  id: '/soins/',
  path: '/soins/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoinsSlugRoute = SoinsSlugRouteImport.update({
  id: '/soins/$slug',
  path: '/soins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bien-etre': typeof BienEtreRoute
  '/concept': typeof ConceptRoute
  '/contact': typeof ContactRoute
  '/cryolipolyse-dole': typeof CryolipolyseDoleRoute
  '/cryolipolyse-ventre-dole': typeof CryolipolyseVentreDoleRoute
  '/epilation-laser-dole': typeof EpilationLaserDoleRoute
  '/epilation-laser-jambes-dole': typeof EpilationLaserJambesDoleRoute
  '/epilation-laser-maillot-dole': typeof EpilationLaserMaillotDoleRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solution-minceur-dole': typeof SolutionMinceurDoleRoute
  '/yoga-dole': typeof YogaDoleRoute
  '/admin/config.yml': typeof AdminConfigDotymlRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/soins/$slug': typeof SoinsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/soins/': typeof SoinsIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bien-etre': typeof BienEtreRoute
  '/concept': typeof ConceptRoute
  '/contact': typeof ContactRoute
  '/cryolipolyse-dole': typeof CryolipolyseDoleRoute
  '/cryolipolyse-ventre-dole': typeof CryolipolyseVentreDoleRoute
  '/epilation-laser-dole': typeof EpilationLaserDoleRoute
  '/epilation-laser-jambes-dole': typeof EpilationLaserJambesDoleRoute
  '/epilation-laser-maillot-dole': typeof EpilationLaserMaillotDoleRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solution-minceur-dole': typeof SolutionMinceurDoleRoute
  '/yoga-dole': typeof YogaDoleRoute
  '/admin/config.yml': typeof AdminConfigDotymlRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/soins/$slug': typeof SoinsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/soins': typeof SoinsIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bien-etre': typeof BienEtreRoute
  '/concept': typeof ConceptRoute
  '/contact': typeof ContactRoute
  '/cryolipolyse-dole': typeof CryolipolyseDoleRoute
  '/cryolipolyse-ventre-dole': typeof CryolipolyseVentreDoleRoute
  '/epilation-laser-dole': typeof EpilationLaserDoleRoute
  '/epilation-laser-jambes-dole': typeof EpilationLaserJambesDoleRoute
  '/epilation-laser-maillot-dole': typeof EpilationLaserMaillotDoleRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solution-minceur-dole': typeof SolutionMinceurDoleRoute
  '/yoga-dole': typeof YogaDoleRoute
  '/admin/config.yml': typeof AdminConfigDotymlRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/soins/$slug': typeof SoinsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/soins/': typeof SoinsIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bien-etre'
    | '/concept'
    | '/contact'
    | '/cryolipolyse-dole'
    | '/cryolipolyse-ventre-dole'
    | '/epilation-laser-dole'
    | '/epilation-laser-jambes-dole'
    | '/epilation-laser-maillot-dole'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/solution-minceur-dole'
    | '/yoga-dole'
    | '/admin/config.yml'
    | '/api/auth'
    | '/blog/$slug'
    | '/soins/$slug'
    | '/blog/'
    | '/soins/'
    | '/api/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bien-etre'
    | '/concept'
    | '/contact'
    | '/cryolipolyse-dole'
    | '/cryolipolyse-ventre-dole'
    | '/epilation-laser-dole'
    | '/epilation-laser-jambes-dole'
    | '/epilation-laser-maillot-dole'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/solution-minceur-dole'
    | '/yoga-dole'
    | '/admin/config.yml'
    | '/api/auth'
    | '/blog/$slug'
    | '/soins/$slug'
    | '/blog'
    | '/soins'
    | '/api/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/bien-etre'
    | '/concept'
    | '/contact'
    | '/cryolipolyse-dole'
    | '/cryolipolyse-ventre-dole'
    | '/epilation-laser-dole'
    | '/epilation-laser-jambes-dole'
    | '/epilation-laser-maillot-dole'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/solution-minceur-dole'
    | '/yoga-dole'
    | '/admin/config.yml'
    | '/api/auth'
    | '/blog/$slug'
    | '/soins/$slug'
    | '/blog/'
    | '/soins/'
    | '/api/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BienEtreRoute: typeof BienEtreRoute
  ConceptRoute: typeof ConceptRoute
  ContactRoute: typeof ContactRoute
  CryolipolyseDoleRoute: typeof CryolipolyseDoleRoute
  CryolipolyseVentreDoleRoute: typeof CryolipolyseVentreDoleRoute
  EpilationLaserDoleRoute: typeof EpilationLaserDoleRoute
  EpilationLaserJambesDoleRoute: typeof EpilationLaserJambesDoleRoute
  EpilationLaserMaillotDoleRoute: typeof EpilationLaserMaillotDoleRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionMinceurDoleRoute: typeof SolutionMinceurDoleRoute
  YogaDoleRoute: typeof YogaDoleRoute
  AdminConfigDotymlRoute: typeof AdminConfigDotymlRoute
  ApiAuthRoute: typeof ApiAuthRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  SoinsSlugRoute: typeof SoinsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SoinsIndexRoute: typeof SoinsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bien-etre': {
      id: '/bien-etre'
      path: '/bien-etre'
      fullPath: '/bien-etre'
      preLoaderRoute: typeof BienEtreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept': {
      id: '/concept'
      path: '/concept'
      fullPath: '/concept'
      preLoaderRoute: typeof ConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cryolipolyse-dole': {
      id: '/cryolipolyse-dole'
      path: '/cryolipolyse-dole'
      fullPath: '/cryolipolyse-dole'
      preLoaderRoute: typeof CryolipolyseDoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cryolipolyse-ventre-dole': {
      id: '/cryolipolyse-ventre-dole'
      path: '/cryolipolyse-ventre-dole'
      fullPath: '/cryolipolyse-ventre-dole'
      preLoaderRoute: typeof CryolipolyseVentreDoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epilation-laser-dole': {
      id: '/epilation-laser-dole'
      path: '/epilation-laser-dole'
      fullPath: '/epilation-laser-dole'
      preLoaderRoute: typeof EpilationLaserDoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epilation-laser-jambes-dole': {
      id: '/epilation-laser-jambes-dole'
      path: '/epilation-laser-jambes-dole'
      fullPath: '/epilation-laser-jambes-dole'
      preLoaderRoute: typeof EpilationLaserJambesDoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epilation-laser-maillot-dole': {
      id: '/epilation-laser-maillot-dole'
      path: '/epilation-laser-maillot-dole'
      fullPath: '/epilation-laser-maillot-dole'
      preLoaderRoute: typeof EpilationLaserMaillotDoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solution-minceur-dole': {
      id: '/solution-minceur-dole'
      path: '/solution-minceur-dole'
      fullPath: '/solution-minceur-dole'
      preLoaderRoute: typeof SolutionMinceurDoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga-dole': {
      id: '/yoga-dole'
      path: '/yoga-dole'
      fullPath: '/yoga-dole'
      preLoaderRoute: typeof YogaDoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config.yml': {
      id: '/admin/config.yml'
      path: '/admin/config.yml'
      fullPath: '/admin/config.yml'
      preLoaderRoute: typeof AdminConfigDotymlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soins/': {
      id: '/soins/'
      path: '/soins'
      fullPath: '/soins/'
      preLoaderRoute: typeof SoinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soins/$slug': {
      id: '/soins/$slug'
      path: '/soins/$slug'
      fullPath: '/soins/$slug'
      preLoaderRoute: typeof SoinsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof ApiAuthRoute
    }
  }
}

interface ApiAuthRouteChildren {
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

const ApiAuthRouteChildren: ApiAuthRouteChildren = {
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}

const ApiAuthRouteWithChildren =
  ApiAuthRoute._addFileChildren(ApiAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BienEtreRoute: BienEtreRoute,
  ConceptRoute: ConceptRoute,
  ContactRoute: ContactRoute,
  CryolipolyseDoleRoute: CryolipolyseDoleRoute,
  CryolipolyseVentreDoleRoute: CryolipolyseVentreDoleRoute,
  EpilationLaserDoleRoute: EpilationLaserDoleRoute,
  EpilationLaserJambesDoleRoute: EpilationLaserJambesDoleRoute,
  EpilationLaserMaillotDoleRoute: EpilationLaserMaillotDoleRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionMinceurDoleRoute: SolutionMinceurDoleRoute,
  YogaDoleRoute: YogaDoleRoute,
  AdminConfigDotymlRoute: AdminConfigDotymlRoute,
  ApiAuthRoute: ApiAuthRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  SoinsSlugRoute: SoinsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  SoinsIndexRoute: SoinsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
